version: "3.8"
services:
  phpmyadmin:
    image: phpmyadmin:5-apache
    container_name: myadmin
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_PORT: ${MYSQL_PORT}
      PMA_ARBITRARY: "1"
      UPLOAD_LIMIT: 64M
    # ถ้าจะล็อกอินอัตโนมัติ (ไม่แนะนำในที่สาธารณะ):
    #   PMA_USER: ${MYSQL_USER}
    #   PMA_PASSWORD: ${MYSQL_PASS}
